name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build:ui --if-present
    - run: cd /home/ubuntu/actions-runner-Approvals/approvals/DIGITALHUB/DIGITALHUB/uimodule/dist
    - run: mv /home/ubuntu/actions-runner-Approvals/approvals/DIGITALHUB/DIGITALHUB/uimodule/dist /home/ubuntu/actions-runner-Approvals/approvals/DIGITALHUB/DIGITALHUB/uimodule/DIGITALHUB
    - run: sudo cp -avr /home/ubuntu/actions-runner-Approvals/approvals/DIGITALHUB/DIGITALHUB/uimodule/DIGITALHUB /var/www/html/Approvals
